import type { Metadata } from "next";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { Bai_Jamjuree } from 'next/font/google'
import { Josefin_Sans } from "next/font/google";
import { Alata } from "next/font/google";
// Import Font Awesome CSS
config.autoAddCss = false;

const baiJamjure = Bai_Jamjuree({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-sans'
});

const fontJoseFIn = Josefin_Sans({
  weight: ['200', '300', '400', '500', '600', '700'],
  subsets: ['latin'],
variable: '--font-josefin'
});

const AlataFont = Alata({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-alata'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${baiJamjure.variable} ${fontJoseFIn.variable}
        ${AlataFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
